name: Deploy Cloud Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy with Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: node build.mjs ${{ secrets.IBM_API_KEY }} ${{ secrets.IBM_FUNCTIONS_NAMESPACE }}
